Add post about InnoDB row format compression with MySQL
karriereat/dev-blog pull request #12
Opened 2017-02-20 13:49 UTC by jaylinski

🗄  ✂️

2017-02-20 14:51 UTC, jaylinski commented
Already reviewed by Christoph.

2017-02-21 05:53 UTC, fetzi requested changes
Cooler Artikel, bitte noch das Datum anpassen 😁

2017-02-21 16:37 UTC, jaylinski commented
@fetzi whoops, ist gefixed.

2017-02-21 18:48 UTC, fetzi approved these changes

2017-02-21 18:48 UTC, merged