Add post about Laracon EU 2017
karriereat/dev-blog pull request #21
Opened 2017-10-05 07:50 UTC by jaylinski

🐘

2017-10-05 07:53 UTC, fetzi requested changes
Evtl. noch an Link zur YouTube Playlist mit allen Talks?

2017-10-05 07:53 UTC, fetzi commented on _posts/2017-09-10-laracon-eu-2017.md
> +Wir verwenden bei [karriere.at](https://www.karriere.at/) seit einiger Zeit das PHP-Framework [Laravel](https://laravel.com/) um Applikation für unsere User und Kunden zu programmieren.
Applikationen

2017-10-05 08:50 UTC, otsch commented on _posts/2017-09-10-laracon-eu-2017.md
> +In diesem Video seht einen kurzen Zusammenschnitt der Konferenz:
seht ihr

2017-10-05 08:50 UTC, otsch commented on _posts/2017-09-10-laracon-eu-2017.md
> +Am zweiten Tag der Konferenz startete Taylor Otwell mit der viel erwarteten Key-Note zu den neuen Features in Laravel 5.5.
eventuell "mit der mit Spannung erwarteten"?

2017-10-05 18:26 UTC, jaylinski commented on _posts/2017-09-10-laracon-eu-2017.md
> +In diesem Video seht einen kurzen Zusammenschnitt der Konferenz:
thx, fixed

2017-10-05 18:27 UTC, jaylinski commented on _posts/2017-09-10-laracon-eu-2017.md
> +Am zweiten Tag der Konferenz startete Taylor Otwell mit der viel erwarteten Key-Note zu den neuen Features in Laravel 5.5.
stimmt, klingt besser :) ist geändert.

2017-10-05 18:27 UTC, jaylinski commented on _posts/2017-09-10-laracon-eu-2017.md
> +Wir verwenden bei [karriere.at](https://www.karriere.at/) seit einiger Zeit das PHP-Framework [Laravel](https://laravel.com/) um Applikation für unsere User und Kunden zu programmieren.
thx, fixed

2017-10-05 18:28 UTC, jaylinski commented
@fetzi Hab den Link zur Youtube-Playlist ergänzt.

2017-10-06 07:19 UTC, fetzi approved these changes

2017-10-06 07:21 UTC, fetzi requested changes

2017-10-06 07:21 UTC, fetzi commented on _posts/2017-09-10-laracon-eu-2017.md
> +Um unser Wissen in das Framework zu vertiefen, besuchten wir vom 28. bis 30. August die [Laracon EU](https://laracon.eu/) in Amsterdam.
Um unser Wissen im Laravel Framework zu vertiefen

2017-10-06 11:50 UTC, jaylinski commented on _posts/2017-09-10-laracon-eu-2017.md
> +Um unser Wissen in das Framework zu vertiefen, besuchten wir vom 28. bis 30. August die [Laracon EU](https://laracon.eu/) in Amsterdam.
Done!

2017-10-06 12:41 UTC, fetzi approved these changes

2017-10-06 12:41 UTC, merged